In [1]:

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [200]:
#direct numerical calculations
24 * 7

168

In [201]:
#easy variables
hours_in_a_week = 24 * 7

In [202]:
hours_in_a_week

168

In [203]:
hours_in_a_week * 100

16800

Terminology: expressions, values, names, variables, statements

Naming rules: letters, numbers, underscores; case sensitive; start with letter usually

Calculate the number of seconds in a year.

In [204]:
60 * 60 * 24 * 365

31536000

In [205]:
seconds_per_year = 60 * 60 * 24 * 365

In [206]:
seconds_per_year

31536000

In [207]:
seconds_per_hour = 60 * 60
hours_per_year = 24 * 365
seconds_per_year = seconds_per_hour * hours_per_year
seconds_per_year

31536000

In [208]:
import datetime as dt
import time as tm

In [209]:
tm.time() 
#current time in sec since jan1970

1599145306.082999

In [210]:
today = dt.date.today()
print(today)

2020-09-03


In [211]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow.hour

10

In [212]:
type('hi')

str

In [213]:
type('1000.00')

str

In [214]:
type(1000.00)

float

In [215]:
type(1000)

int

In [216]:
u = [1, 2, 3]

In [217]:
type(u)

list

In [218]:
v=(1,2,3)
type(v)

tuple

In [219]:
u.append(4)
u

[1, 2, 3, 4]

In [220]:
#built in functions
abs(-5)

5

In [221]:
abs(3-8)

5

In [222]:
max(3,4)

4

In [223]:
y = max(3,4)

In [224]:
y

4

In [225]:
y = min(3,4)
y

3

In [226]:
def adding(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

In [227]:
print(adding(3, 4))


7


In [228]:
print(adding(3, 4, 5))

12


In [229]:
f=adding

In [230]:
f(6,3)

9

In [231]:
f2 = lambda a, b : max(a,b)
f2(8,9)

9

In [232]:
f2 = lambda a, b,c : a-b*c
f2(8,9,2)

-10

In [1]:
x=[1,2,3]
x[0]

1

In [234]:
x[-1]

3

In [235]:
sum=0
for item in x:
    item+=1
    sum = sum+item
    print(item)
    
 
   

2
3
4


In [236]:
print(sum)


9


In [5]:
len(x)

3

In [6]:

##Numpy


In [7]:

ar = np.array(x)
ar

array([1, 2, 3])

In [8]:
nr = np.arange(0, 12, 3) # start at 0 count up by 3, stop before 12
nr

array([0, 3, 6, 9])

In [9]:
yy=nr**2
yy

array([ 0,  9, 36, 81])

In [10]:
nr.shape

(4,)

In [11]:
len(nr)

4

In [12]:
uu = np.linspace(0, 1, 4) # return 4 evenly spaced values from 0 to 1
uu

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [13]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
a = np.matrix('-3 -2 -1;1 2 3')
a

matrix([[-3, -2, -1],
        [ 1,  2,  3]])

In [17]:
a[a <1] = 0
a

matrix([[0, 0, 0],
        [1, 2, 3]])

In [18]:
a[1,1]

2

In [19]:
a[:1, :-1]

matrix([[0, 0]])

In [20]:
a.shape

(2, 3)

In [21]:
at=a.T
np.shape(at)

(3, 2)

In [22]:
 u=np.random.randint(0, 4, (3,2))
u
    

array([[2, 2],
       [0, 3],
       [1, 0]])

<b>Pandas!</b>

In [23]:
names = ['Matt', 'Jack', 'Nancy']
pd.Series(names)

0     Matt
1     Jack
2    Nancy
dtype: object

In [24]:
numbers = [0, 3,7]
pd.Series(numbers)

0    0
1    3
2    7
dtype: int64

In [25]:
students={'student1':'Matt','student2':'Jack','student3':'Nancy'}
pd.Series(students)

student1     Matt
student2     Jack
student3    Nancy
dtype: object

In [26]:
u=pd.Series(names, index=['student1', 'student2', 'student3'])
u

student1     Matt
student2     Jack
student3    Nancy
dtype: object

In [27]:
u.loc['student1']

'Matt'

In [28]:
u.iloc[2]

'Nancy'

In [29]:
np.size(u)

3

In [30]:
u2=pd.Series([100,89,90], index=['student1', 'student2', 'student3'])
u2

student1    100
student2     89
student3     90
dtype: int64

In [31]:
np.sum(u2)

279

In [32]:
import pandas as pd
Course_details1 = pd.Series({'Name': 'Matt',
                        'Place of birth': 'Wisconsin',
                        'Final score': 92})
Course_details2 = pd.Series({'Name': 'Jack',
                        'Place of birth': 'Minnesota',
                        'Final score': 88})
Course_details3= pd.Series({'Name': 'Nancy',
                        'Place of birth': 'Florida',
                        'Final score': 84})
Course_details4= pd.Series({'Name': 'Nora',
                        'Place of birth': 'Wisconsin',
                        'Final score': 87})
df = pd.DataFrame([Course_details1, Course_details2, Course_details3, Course_details4], index=['Course 1', 'Course 2', 'Course 2', 'Course 1'])
df.head()

Name Place of birth  Final score
Course 1   Matt      Wisconsin           92
Course 2   Jack      Minnesota           88
Course 2  Nancy        Florida           84
Course 1   Nora      Wisconsin           87